### ISSUE TITLE
[Question] can i use page-ui for my template product?

### ISSUE THREAD

**Issue by yassinebridi** [danmindru/page-ui#4]
first of all, thank's for open sourcing these wonderful components.

I know this is licenced under MIT but wanted to ask permission first.
I'm building a template for sale for a specific use case, and i'm blocked at making home page marketing demos, and wanted to use your components for that.

Thanks.

**Comment by danmindru** [comment]
hi @yassinebridi.
Very nice of you to ask! Sure go ahead and use them. If possible, I’d appreciate a link back to [pageui.dev](https://pageui.dev) 🙏

**Comment by yassinebridi** [comment]
I will definitely add that to the acknowledgement, thanks 🙏
