### ISSUE TITLE
Missing chart components

### ISSUE THREAD

**Issue by josemiguelq** [danmindru/page-ui#7]
There are some examples in doc that import ui/chart and this path dont exists

```
import {
  ChartConfig,
  ChartContainer,
  ChartTooltip,
  ChartTooltipContent,
} from "@/components/shared/ui/chart"
```

Is there a way to get those components?

**Comment by danmindru** [comment]
Hi @josemiguelq, you can get those from here:

https://github.com/shadcn-ui/ui/blob/main/apps/www/registry/default/ui/chart.tsx

Please note you need `recharts` as a dependency
